//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab_23.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Item
    {
        [Key]
        public int Id { get; set; }
        [MaxLength (20)]
        public string Name { get; set; }
        [MaxLength (2000)]
        public string Description { get; set; }
        [Required]
        public string Quantity { get; set; }
        [Required]
        public Nullable<decimal> Price { get; set; }
    }
}
